/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Shamal
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpMain = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnChefSummery = new javax.swing.JMenu();
        mnTpoperator = new javax.swing.JMenu();
        mnChef = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout dpMainLayout = new javax.swing.GroupLayout(dpMain);
        dpMain.setLayout(dpMainLayout);
        dpMainLayout.setHorizontalGroup(
            dpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1103, Short.MAX_VALUE)
        );
        dpMainLayout.setVerticalGroup(
            dpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        mnChefSummery.setText("Chef Summery");
        mnChefSummery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnChefSummeryMouseClicked(evt);
            }
        });
        mnChefSummery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnChefSummeryActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnChefSummery);

        mnTpoperator.setText("Telephone operator");
        mnTpoperator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnTpoperatorMouseClicked(evt);
            }
        });
        mnTpoperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTpoperatorActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnTpoperator);

        mnChef.setText("Chef");
        mnChef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnChefMouseClicked(evt);
            }
        });
        mnChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnChefActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnChef);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMain)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnChefSummeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnChefSummeryActionPerformed

    }//GEN-LAST:event_mnChefSummeryActionPerformed

    private void mnTpoperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTpoperatorActionPerformed

    }//GEN-LAST:event_mnTpoperatorActionPerformed

    private void mnChefSummeryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnChefSummeryMouseClicked
        dpMain.removeAll();
        dpMain.repaint();
        dpMain.add(new ChefSummery()).setVisible(true);
    }//GEN-LAST:event_mnChefSummeryMouseClicked

    private void mnTpoperatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnTpoperatorMouseClicked
        dpMain.removeAll();
        dpMain.repaint();
        dpMain.add(new TPOperatorReport()).setVisible(true);
    }//GEN-LAST:event_mnTpoperatorMouseClicked

    private void mnChefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnChefMouseClicked
        dpMain.removeAll();
        dpMain.repaint();
        dpMain.add(new ChefReport()).setVisible(true);
    }//GEN-LAST:event_mnChefMouseClicked

    private void mnChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnChefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnChefActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpMain;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnChef;
    private javax.swing.JMenu mnChefSummery;
    private javax.swing.JMenu mnTpoperator;
    // End of variables declaration//GEN-END:variables
}
